language: node_js
node_js: stable
before_install:
# - openssl aes-256-cbc -K $encrypted_ef7aaa76ab5b_key -iv $encrypted_ef7aaa76ab5b_iv
#   -in id_rsa_blog.enc -out .\\.travis\\id_rsa_blog -d
- openssl aes-256-cbc -K $encrypted_ef7aaa76ab5b_key -iv $encrypted_ef7aaa76ab5b_iv
  -in id_rsa_blog.enc -out ~/.ssh/id_rsa -d

- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config


- npm install -g hexo
- npm install -g hexo-cli
- npm install --save hexo-deployer-git
- npm install --save-dev hexo-util
- export TZ='Asia/Shanghai'
before_script: 
install:
- npm install
script:
- hexo clean
- hexo g
after_script:
- git clone https://${GH_REF} .deploy_git
- echo "$T_Token"
- cd .deploy_git
- git checkout master
- ls
- cd ../
- mv .deploy_git/.git/ ./public/
- cd ./public
- ls
- git config --global credential.helper cache
- git config --global credential.helper store
- git config user.name "ShoutangYang"
- git config user.email "to_yst@163.com"
- git remote -v
- ssh -T git@github.com
- git add .
- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
- ls
- git push --force --quiet https://a34917421a940391b77fcca14f56166b8be2cde4@github.com/ShoutangYang/ShoutangYang.github.io.git
  master:master
- ls
branches:
  only:
  - dev
env:
  global:
  - GH_REF: github.com/ShoutangYang/ShoutangYang.github.io.git
notifications:
  email:
  - to_yst@163.com
  on_success: change
  on_failure: always
