language: node_js
node_js: stable
before_install:

- npm install -g hexo
- npm install -g hexo-cli
- npm install --save hexo-deployer-git
- npm install --save-dev hexo-util
- export TZ='Asia/Shanghai'

before_script: 
- git config user.name "TravisCI"
- git config user.email "to_yst@163.com"
- git config --global push.default simple

install:
- npm install
script:
- hexo clean
- hexo g
after_script:

- git clone --branch master https://${GH_REF} .deploy_git
- echo "$T_Token"
- echo "$GITHUB_TOKEN"
- ls
- cd .deploy_git
- git checkout master
- ls
- cd ../
- mv .deploy_git/.git/ ./public/
- cd ./public
- ls
# - git config --global credential.helper cache
# - git config --global credential.helper store

# - git config user.name "ShoutangYang"
# - git config user.email "to_yst@163.com"
- git remote -v
- ssh -T git@github.com
- git add .
- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
- ls
- git push --force --quiet https://ShoutangYang:$GITHUB_TOKEN@github.com/ShoutangYang/ShoutangYang.github.io.git
   

- ls
branches:
  only:
  - dev
env:
  global:
  - GH_REF: github.com/ShoutangYang/ShoutangYang.github.io.git
notifications:
  email:
  - to_yst@163.com
  on_success: change
  on_failure: always



